### ISSUE TITLE
Copying content to coronasafe 

### ISSUE THREAD

**Issue by bodhish** [AllenAJ/Corona-#1]
Will you be interested in porting this content to coronasafe.in

github.com/coronasafe/coronasafe.in

**Comment by AllenAJ** [comment]
Surely. @bodhish .
I'm interested in knowing the procedure.

**Comment by bodhish** [comment]
Can you make a PR `coronasafe/coronasafe.in`

This doc covers the steps. 

https://www.coronasafe.in/contribute

**Comment by AllenAJ** [comment]
Great!
