### ISSUE TITLE
Adding few more platforms

### ISSUE THREAD

**Issue by kaiiyer** [AllenAJ/Corona-#3]
[Citrix](https://www.citrix.com/products/citrix-virtual-apps-and-desktops/resources/datasheet.html)
[SAPJam](https://www.sap.com/products/enterprise-social-collaboration.html)
[Mural](https://mural.co/)
[StatusHero](https://statushero.com/)
[Workplace](https://www.facebook.com/workplace)
[Blackberry Workspace](https://www.blackberry.com/us/en/products/blackberry-digital-workplace#empower)
[Igloo](https://www.igloosoftware.com/)

**Comment by AllenAJ** [comment]
Great choice of tools.
I'll be adding it.
